### ISSUE TITLE
Need to specify the C compiler

### ISSUE THREAD

**Issue by wkcosmology** [ChenYangyao/hipp#48]
When I compile the code using
```sh
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/..
```
![image](https://user-images.githubusercontent.com/29885814/114413913-648acc80-9b7c-11eb-8545-ef7a2eb68331.png)

And I need to manually specify the C compiler to make it work.
![image](https://user-images.githubusercontent.com/29885814/114414227-a0259680-9b7c-11eb-9361-daa4683768ef.png)

**Comment by ChenYangyao** [comment]
This problem is typically related to wrongly alias of exported/environmental variables "CC" and "CXX".
In some environments, "CC" is set to "g++". 
Unfortunately "CC" is used by CMake as the C compiler, not the C++ compiler.
Please set "CC" to, for example, "gcc", and set "CXX" to "g++" before running CMake.
